"""provider key columns

Revision ID: 5404219f916c
Revises: b2717bcdfa98
Create Date: 2026-06-12 23:35:55.155338

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5404219f916c"
down_revision: str | Sequence[str] | None = "b2717bcdfa98"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "org_llm_settings", sa.Column("gemini_api_key_encrypted", sa.Text(), nullable=True)
    )
    op.add_column(
        "org_llm_settings", sa.Column("mistral_api_key_encrypted", sa.Text(), nullable=True)
    )
    op.add_column("org_llm_settings", sa.Column("xai_api_key_encrypted", sa.Text(), nullable=True))
    op.add_column(
        "org_llm_settings", sa.Column("deepseek_api_key_encrypted", sa.Text(), nullable=True)
    )
    op.add_column("org_llm_settings", sa.Column("groq_api_key_encrypted", sa.Text(), nullable=True))
    op.add_column(
        "org_llm_settings", sa.Column("openrouter_api_key_encrypted", sa.Text(), nullable=True)
    )
    op.add_column(
        "org_llm_settings", sa.Column("cohere_api_key_encrypted", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("org_llm_settings", "cohere_api_key_encrypted")
    op.drop_column("org_llm_settings", "openrouter_api_key_encrypted")
    op.drop_column("org_llm_settings", "groq_api_key_encrypted")
    op.drop_column("org_llm_settings", "deepseek_api_key_encrypted")
    op.drop_column("org_llm_settings", "xai_api_key_encrypted")
    op.drop_column("org_llm_settings", "mistral_api_key_encrypted")
    op.drop_column("org_llm_settings", "gemini_api_key_encrypted")
    # ### end Alembic commands ###
