"""citations and document metadata

Revision ID: aa303f0035a5
Revises: 753b270b4c37
Create Date: 2026-06-12 11:40:58.253541

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "aa303f0035a5"
down_revision: str | Sequence[str] | None = "753b270b4c37"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_messages",
        sa.Column("citations", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column("documents", sa.Column("title", sa.String(length=255), nullable=True))
    op.add_column("documents", sa.Column("language", sa.String(length=16), nullable=True))
    op.add_column("documents", sa.Column("summary", sa.Text(), nullable=True))
    op.add_column(
        "documents", sa.Column("topics", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "topics")
    op.drop_column("documents", "summary")
    op.drop_column("documents", "language")
    op.drop_column("documents", "title")
    op.drop_column("chat_messages", "citations")
    # ### end Alembic commands ###
