"""organization billing state

Revision ID: b2717bcdfa98
Revises: d87fb1b886f7
Create Date: 2026-06-12 20:30:50.458111

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b2717bcdfa98"
down_revision: str | Sequence[str] | None = "d87fb1b886f7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organizations",
        sa.Column("plan", sa.String(length=16), server_default="free", nullable=False),
    )
    op.add_column(
        "organizations", sa.Column("stripe_customer_id", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "organizations", sa.Column("stripe_subscription_id", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "organizations", sa.Column("subscription_status", sa.String(length=32), nullable=True)
    )
    op.create_unique_constraint(
        op.f("uq_organizations_stripe_customer_id"), "organizations", ["stripe_customer_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_organizations_stripe_customer_id"), "organizations", type_="unique")
    op.drop_column("organizations", "subscription_status")
    op.drop_column("organizations", "stripe_subscription_id")
    op.drop_column("organizations", "stripe_customer_id")
    op.drop_column("organizations", "plan")
    # ### end Alembic commands ###
