"""org llm settings

Revision ID: cadc131ed9f8
Revises: aa303f0035a5
Create Date: 2026-06-12 12:53:38.927374

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cadc131ed9f8"
down_revision: str | Sequence[str] | None = "aa303f0035a5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "org_llm_settings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("chat_provider", sa.String(length=32), nullable=False),
        sa.Column("chat_model", sa.String(length=64), nullable=False),
        sa.Column("embedding_provider", sa.String(length=32), nullable=False),
        sa.Column("anthropic_api_key_encrypted", sa.Text(), nullable=True),
        sa.Column("openai_api_key_encrypted", sa.Text(), nullable=True),
        sa.Column("voyage_api_key_encrypted", sa.Text(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["organizations.id"],
            name=op.f("fk_org_llm_settings_tenant_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_org_llm_settings")),
        sa.UniqueConstraint("tenant_id", name=op.f("uq_org_llm_settings_tenant_id")),
    )
    op.create_index(
        op.f("ix_org_llm_settings_tenant_id"), "org_llm_settings", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_org_llm_settings_tenant_id"), table_name="org_llm_settings")
    op.drop_table("org_llm_settings")
    # ### end Alembic commands ###
