"""org rate limit overrides

Revision ID: d87fb1b886f7
Revises: cadc131ed9f8
Create Date: 2026-06-12 15:24:56.228788

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d87fb1b886f7"
down_revision: str | Sequence[str] | None = "cadc131ed9f8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organizations", sa.Column("rate_limit_rpm_override", sa.Integer(), nullable=True)
    )
    op.add_column(
        "organizations", sa.Column("rate_limit_tpd_override", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organizations", "rate_limit_tpd_override")
    op.drop_column("organizations", "rate_limit_rpm_override")
    # ### end Alembic commands ###
